// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package tnmodel

import "encoding/json"
import "fmt"
import "github.com/atombender/go-jsonschema/pkg/types"
import "github.com/go-viper/mapstructure/v2"
import "reflect"
import "regexp"
import "strings"
import "time"
import "unicode/utf8"

type Date types.SerializableDate

type DateOrDateTime string

type Dependency struct {
	// Gap corresponds to the JSON schema field "gap".
	Gap *IsoDuration `json:"gap,omitempty,omitzero" yaml:"gap,omitempty" mapstructure:"gap,omitempty"`

	// Reltype corresponds to the JSON schema field "reltype".
	Reltype string `json:"reltype" yaml:"reltype" mapstructure:"reltype"`

	// Uid corresponds to the JSON schema field "uid".
	Uid string `json:"uid" yaml:"uid" mapstructure:"uid"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Dependency) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["reltype"]; raw != nil && !ok {
		return fmt.Errorf("field reltype in Dependency: required")
	}
	if _, ok := raw["uid"]; raw != nil && !ok {
		return fmt.Errorf("field uid in Dependency: required")
	}
	type Plain Dependency
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Reltype)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "reltype", 1)
	}
	if utf8.RuneCountInString(string(plain.Uid)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "uid", 1)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = Dependency(plain)
	return nil
}

type IsoDuration string

// UnmarshalJSON implements json.Unmarshaler.
func (j *IsoDuration) UnmarshalJSON(value []byte) error {
	type Plain IsoDuration
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^-?P(?=\d|T\d)(?:\d+Y)?(?:\d+M)?(?:\d+W)?(?:\d+D)?(?:T(?:\d+H)?(?:\d+M)?(?:\d+(?:\.\d+)?S)?)?$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^-?P(?=\d|T\d)(?:\d+Y)?(?:\d+M)?(?:\d+W)?(?:\d+D)?(?:T(?:\d+H)?(?:\d+M)?(?:\d+(?:\.\d+)?S)?)?$`)
	}
	*j = IsoDuration(plain)
	return nil
}

type Reminder interface{}

type TaskFrontmatter struct {
	// BlockedBy corresponds to the JSON schema field "blocked_by".
	BlockedBy []Dependency `json:"blocked_by,omitempty,omitzero" yaml:"blocked_by,omitempty" mapstructure:"blocked_by,omitempty"`

	// CompleteInstances corresponds to the JSON schema field "complete_instances".
	CompleteInstances []Date `json:"complete_instances,omitempty,omitzero" yaml:"complete_instances,omitempty" mapstructure:"complete_instances,omitempty"`

	// CompletedDate corresponds to the JSON schema field "completed_date".
	CompletedDate *Date `json:"completed_date,omitempty,omitzero" yaml:"completed_date,omitempty" mapstructure:"completed_date,omitempty"`

	// Contexts corresponds to the JSON schema field "contexts".
	Contexts []string `json:"contexts,omitempty,omitzero" yaml:"contexts,omitempty" mapstructure:"contexts,omitempty"`

	// DateCreated corresponds to the JSON schema field "date_created".
	DateCreated time.Time `json:"date_created" yaml:"date_created" mapstructure:"date_created"`

	// DateModified corresponds to the JSON schema field "date_modified".
	DateModified time.Time `json:"date_modified" yaml:"date_modified" mapstructure:"date_modified"`

	// Due corresponds to the JSON schema field "due".
	Due *DateOrDateTime `json:"due,omitempty,omitzero" yaml:"due,omitempty" mapstructure:"due,omitempty"`

	// Stable task identity token.
	Id *string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// OccurrenceDate corresponds to the JSON schema field "occurrence_date".
	OccurrenceDate *Date `json:"occurrence_date,omitempty,omitzero" yaml:"occurrence_date,omitempty" mapstructure:"occurrence_date,omitempty"`

	// OccurrenceFutureHorizon corresponds to the JSON schema field
	// "occurrence_future_horizon".
	OccurrenceFutureHorizon *IsoDuration `json:"occurrence_future_horizon,omitempty,omitzero" yaml:"occurrence_future_horizon,omitempty" mapstructure:"occurrence_future_horizon,omitempty"`

	// OccurrenceMaterialization corresponds to the JSON schema field
	// "occurrence_materialization".
	OccurrenceMaterialization *TaskFrontmatterOccurrenceMaterialization `json:"occurrence_materialization,omitempty,omitzero" yaml:"occurrence_materialization,omitempty" mapstructure:"occurrence_materialization,omitempty"`

	// OccurrenceNextTrigger corresponds to the JSON schema field
	// "occurrence_next_trigger".
	OccurrenceNextTrigger *TaskFrontmatterOccurrenceNextTrigger `json:"occurrence_next_trigger,omitempty,omitzero" yaml:"occurrence_next_trigger,omitempty" mapstructure:"occurrence_next_trigger,omitempty"`

	// OccurrencePastHorizon corresponds to the JSON schema field
	// "occurrence_past_horizon".
	OccurrencePastHorizon *IsoDuration `json:"occurrence_past_horizon,omitempty,omitzero" yaml:"occurrence_past_horizon,omitempty" mapstructure:"occurrence_past_horizon,omitempty"`

	// OccurrenceTemplate corresponds to the JSON schema field "occurrence_template".
	OccurrenceTemplate *string `json:"occurrence_template,omitempty,omitzero" yaml:"occurrence_template,omitempty" mapstructure:"occurrence_template,omitempty"`

	// Priority corresponds to the JSON schema field "priority".
	Priority *string `json:"priority,omitempty,omitzero" yaml:"priority,omitempty" mapstructure:"priority,omitempty"`

	// Projects corresponds to the JSON schema field "projects".
	Projects []string `json:"projects,omitempty,omitzero" yaml:"projects,omitempty" mapstructure:"projects,omitempty"`

	// TaskNotes recurrence string.
	Recurrence *string `json:"recurrence,omitempty,omitzero" yaml:"recurrence,omitempty" mapstructure:"recurrence,omitempty"`

	// RecurrenceAnchor corresponds to the JSON schema field "recurrence_anchor".
	RecurrenceAnchor *TaskFrontmatterRecurrenceAnchor `json:"recurrence_anchor,omitempty,omitzero" yaml:"recurrence_anchor,omitempty" mapstructure:"recurrence_anchor,omitempty"`

	// RecurrenceParent corresponds to the JSON schema field "recurrence_parent".
	RecurrenceParent *string `json:"recurrence_parent,omitempty,omitzero" yaml:"recurrence_parent,omitempty" mapstructure:"recurrence_parent,omitempty"`

	// Reminders corresponds to the JSON schema field "reminders".
	Reminders []Reminder `json:"reminders,omitempty,omitzero" yaml:"reminders,omitempty" mapstructure:"reminders,omitempty"`

	// Scheduled corresponds to the JSON schema field "scheduled".
	Scheduled *DateOrDateTime `json:"scheduled,omitempty,omitzero" yaml:"scheduled,omitempty" mapstructure:"scheduled,omitempty"`

	// SkippedInstances corresponds to the JSON schema field "skipped_instances".
	SkippedInstances []Date `json:"skipped_instances,omitempty,omitzero" yaml:"skipped_instances,omitempty" mapstructure:"skipped_instances,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status" yaml:"status" mapstructure:"status"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// TimeEntries corresponds to the JSON schema field "time_entries".
	TimeEntries []TimeEntry `json:"time_entries,omitempty,omitzero" yaml:"time_entries,omitempty" mapstructure:"time_entries,omitempty"`

	// Estimated duration in minutes.
	TimeEstimate *int `json:"time_estimate,omitempty,omitzero" yaml:"time_estimate,omitempty" mapstructure:"time_estimate,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type TaskFrontmatterOccurrenceMaterialization string

const TaskFrontmatterOccurrenceMaterializationManual TaskFrontmatterOccurrenceMaterialization = "manual"
const TaskFrontmatterOccurrenceMaterializationOnCompletion TaskFrontmatterOccurrenceMaterialization = "on_completion"
const TaskFrontmatterOccurrenceMaterializationRolling TaskFrontmatterOccurrenceMaterialization = "rolling"

var enumValues_TaskFrontmatterOccurrenceMaterialization = []interface{}{
	"manual",
	"on_completion",
	"rolling",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskFrontmatterOccurrenceMaterialization) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskFrontmatterOccurrenceMaterialization {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskFrontmatterOccurrenceMaterialization, v)
	}
	*j = TaskFrontmatterOccurrenceMaterialization(v)
	return nil
}

type TaskFrontmatterOccurrenceNextTrigger string

const TaskFrontmatterOccurrenceNextTriggerCompletion TaskFrontmatterOccurrenceNextTrigger = "completion"
const TaskFrontmatterOccurrenceNextTriggerCompletionOrSkip TaskFrontmatterOccurrenceNextTrigger = "completion_or_skip"

var enumValues_TaskFrontmatterOccurrenceNextTrigger = []interface{}{
	"completion",
	"completion_or_skip",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskFrontmatterOccurrenceNextTrigger) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskFrontmatterOccurrenceNextTrigger {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskFrontmatterOccurrenceNextTrigger, v)
	}
	*j = TaskFrontmatterOccurrenceNextTrigger(v)
	return nil
}

type TaskFrontmatterRecurrenceAnchor string

const TaskFrontmatterRecurrenceAnchorCompletion TaskFrontmatterRecurrenceAnchor = "completion"
const TaskFrontmatterRecurrenceAnchorScheduled TaskFrontmatterRecurrenceAnchor = "scheduled"

var enumValues_TaskFrontmatterRecurrenceAnchor = []interface{}{
	"scheduled",
	"completion",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskFrontmatterRecurrenceAnchor) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskFrontmatterRecurrenceAnchor {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskFrontmatterRecurrenceAnchor, v)
	}
	*j = TaskFrontmatterRecurrenceAnchor(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskFrontmatter) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["date_created"]; raw != nil && !ok {
		return fmt.Errorf("field date_created in TaskFrontmatter: required")
	}
	if _, ok := raw["date_modified"]; raw != nil && !ok {
		return fmt.Errorf("field date_modified in TaskFrontmatter: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in TaskFrontmatter: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in TaskFrontmatter: required")
	}
	type Plain TaskFrontmatter
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Id != nil && utf8.RuneCountInString(string(*plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Status)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "status", 1)
	}
	if plain.TimeEstimate != nil && 0 > *plain.TimeEstimate {
		return fmt.Errorf("field %s: must be >= %v", "time_estimate", 0)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = TaskFrontmatter(plain)
	return nil
}

type TasknoteSchemaJson struct {
	// Freeform markdown body. Non-normative for task semantics.
	Body *string `json:"body,omitempty,omitzero" yaml:"body,omitempty" mapstructure:"body,omitempty"`

	// File corresponds to the JSON schema field "file".
	File *TasknoteSchemaJsonFile `json:"file,omitempty,omitzero" yaml:"file,omitempty" mapstructure:"file,omitempty"`

	// Frontmatter corresponds to the JSON schema field "frontmatter".
	Frontmatter TaskFrontmatter `json:"frontmatter" yaml:"frontmatter" mapstructure:"frontmatter"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type TasknoteSchemaJsonFile struct {
	// Created corresponds to the JSON schema field "created".
	Created *time.Time `json:"created,omitempty,omitzero" yaml:"created,omitempty" mapstructure:"created,omitempty"`

	// Modified corresponds to the JSON schema field "modified".
	Modified *time.Time `json:"modified,omitempty,omitzero" yaml:"modified,omitempty" mapstructure:"modified,omitempty"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty,omitzero" yaml:"path,omitempty" mapstructure:"path,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TasknoteSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["frontmatter"]; raw != nil && !ok {
		return fmt.Errorf("field frontmatter in TasknoteSchemaJson: required")
	}
	type Plain TasknoteSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = TasknoteSchemaJson(plain)
	return nil
}

type TimeEntry struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// EndTime corresponds to the JSON schema field "endTime".
	EndTime *time.Time `json:"endTime,omitempty,omitzero" yaml:"endTime,omitempty" mapstructure:"endTime,omitempty"`

	// StartTime corresponds to the JSON schema field "startTime".
	StartTime time.Time `json:"startTime" yaml:"startTime" mapstructure:"startTime"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TimeEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["startTime"]; raw != nil && !ok {
		return fmt.Errorf("field startTime in TimeEntry: required")
	}
	type Plain TimeEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TimeEntry(plain)
	return nil
}
